driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  network:
    - ["private_network", { ip: "192.168.33.10" }]
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - apt::default
      - jenkins::java
  #- name: centos-6.4
  #  run_list:
  #    - yum::default
  #    - jenkins::java

provisioner:
    name: chef_zero
    require_chef_omnibus: true

suites:
  - name: jenkins-chef-dsl
    run_list: jenkins-chef-dsl::default
    attributes:
      jenkins:
        master:
          host: localhost
          install_method: package
